### ISSUE TITLE
RTM: Fix flaky pipeline test (or remove entirely after RTM?)

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1134]
Re: #1115 

`starts a run for a given AttemptRun and executes its on_job_failure downstream job` is flaking: https://app.circleci.com/pipelines/github/OpenFn/Lightning/4269/workflows/95431379-1a49-4879-a85c-cd57584654fa/jobs/21998/tests#failed-test-0

Use seed: `Randomized with seed 931746`

```
error: constraint error when attempting to insert struct:

    * "jobs_name_workflow_id_index" (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.

5) test process/1 starts a run for a given AttemptRun and executes its on_job_failure downstream job (Lightning.PipelineTest)
     test/lightning/pipeline_test.exs:12
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
     
         * "jobs_name_workflow_id_index" (unique_constraint)
     
     If you would like to stop this constraint violation from raising an
     exception and instead add it as an error to your changeset, please
     call `unique_constraint/3` on your changeset with the constraint
     `:name` as an option.
     
     The changeset has not defined any constraint.
     
     code: insert(:job,
     stacktrace:
       (ecto 3.10.2) lib/ecto/repo/schema.ex:804: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
       (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
       (ecto 3.10.2) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.constraints_to_errors/3
       (ecto 3.10.2) lib/ecto/repo/schema.ex:769: Ecto.Repo.Schema.apply/4
       (ecto 3.10.2) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.10.2) lib/ecto/repo/schema.ex:1004: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
       (ecto 3.10.2) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
       test/lightning/pipeline_test.exs:23: (test)
```

**Comment by taylordowns2000** [comment]
closed in `v0.10.0`
