### ISSUE TITLE
Can not edit project name in superuser section

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/Lightning#1239]
**Describe the bug** 
As a project owner i can not edit project name when editing a project name. I have reproduced this locally on main:  the commit sha: `fc0c3080e`

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'Admin settings'
2. Click on 'Edit' on any existing project
3. Type a new project name
4. See error logs from your terminal 👇🏽 
    <details>
    <summary> Error logs </summary>
    
      ```
      [error] GenServer #PID<0.3079.0> terminating
      ** (RuntimeError) you are attempting to change relation :project_users of
      Lightning.Projects.Project but the `:on_replace` option of this relation
      is set to `:raise`.
      
      By default it is not possible to replace or delete embeds and
      associations during `cast`. Therefore Ecto requires the parameters
      given to `cast` to have IDs matching the data currently associated
      to Lightning.Projects.Project. Failing to do so results in this error message.
      
      If you want to replace data or automatically delete any data
      not sent to `cast`, please set the appropriate `:on_replace`
      option when defining the relation. The docs for `Ecto.Changeset`
      covers the supported options in the "Associations, embeds and on
      replace" section.
      
      However, if you don't want to allow data to be replaced or
      deleted, only updated, make sure that:
      
        * If you are attempting to update an existing entry, you
          are including the entry primary key (ID) in the data.
      
        * If you have a relationship with many children, all children
          must be given on update.
      
      
          (ecto 3.10.2) lib/ecto/changeset/relation.ex:246: Ecto.Changeset.Relation.on_replace/2
          (ecto 3.10.2) lib/ecto/changeset/relation.ex:417: Ecto.Changeset.Relation.reduce_delete_changesets/5
          (ecto 3.10.2) lib/ecto/changeset/relation.ex:112: Ecto.Changeset.Relation.cast/5
          (ecto 3.10.2) lib/ecto/changeset.ex:1192: Ecto.Changeset.cast_relation/4
          (lightning 0.9.3) lib/lightning/projects/project.ex:41: Lightning.Projects.Project.changeset/2
          (lightning 0.9.3) lib/lightning_web/live/project_live/form_component.ex:50: LightningWeb.ProjectLive.FormComponent.handle_event/3
          (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:716: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
          (telemetry 1.2.1) /Users/openfn/Workspace/Lightning/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
          (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
          (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:639: Phoenix.LiveView.Channel.component_handle_event/6
          (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
          (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
          (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
      Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5H6GuqzkWHinTwB", event: "event", payload: %{"cid" => 1, "event" => "validate", "type" => "form", "uploads" => %{}, "value" => "project%5Bname%5D=instant-demo&project%5Braw_name%5D=instant-demoa&project%5Bproject_users%5D%5B0%5D%5Brole%5D=owner&project%5Bproject_users%5D%5B0%5D%5Buser_id%5D=e4808008-febc-47e9-a38d-f6073145ec8f&project%5Bproject_users%5D%5B0%5D%5Bdelete%5D=&_target=project%5Braw_name%5D"}, ref: "12", join_ref: "11"}
      State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F5H6GuqzkWHinTwB", endpoint: LightningWeb.Endpoint, view: LightningWeb.ProjectLive.Index, parent_pid: nil, root_pid: #PID<0.3079.0>, router: LightningWeb.Router, assigns: %{project: %Lightning.Projects.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, id: "30947d8a-ed01-458a-a919-37940fc64e91", name: "instant-demo", description: nil, scheduled_deletion: nil, requires_mfa: false, project_users: [%Lightning.Projects.ProjectUser{__meta__: #Ecto.Schema.Metadata<:loaded, "project_users">, id: "03dbb36e-cea0-4f81-9c61-723c4dd58004", user_id: "e4808008-febc-47e9-a38d-f6073145ec8f", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "e4808008-febc-47e9-a38d-f6073145ec8f", first_name: "Ye", last_name: "Bo", email: "yebo@gmail.com", confirmed_at: nil, role: :superuser, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-10-27 13:01:05], updated_at: ~N[2023-10-27 13:01:05], ...>, project_id: "30947d8a-ed01-458a-a919-37940fc64e91", project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: nil, failure_alert: true, role: :owner, digest: :weekly, inserted_at: ~N[2023-10-27 13:01:58], updated_at: ~N[2023-10-27 13:01:58]}], users: #Ecto.Association.NotLoaded<association :users is not loaded>, project_credentials: #Ecto.Association.NotLoaded<association :project_credentials is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, workflows: #Ecto.Association.NotLoaded<association :workflows is not loaded>, jobs: #Ecto.Association.NotLoaded<association :jobs is not loaded>, inserted_at: ~N[2023-10-27 13:01:58], updated_at: ~N[2023-10-27 13:01:58]}, __changed__: %{}, flash: %{}, active_menu_item: :projects, users: [#Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "a318f2a4-deb4-4bf9-aa73-b5a16712cc3b", first_name: nil, last_name: nil, email: "admin@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-10-27 12:57:56], updated_at: ~N[2023-10-27 12:57:56], ...>, #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "bbddc597-bd15-49a7-9046-2facbd69c76b", first_name: nil, last_name: nil, email: "user1@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-10-27 12:57:56], updated_at: ~N[2023-10-27 12:57:56], ...>, #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "15d5191f-7d13-4e27-adda-e40e7473248e", first_name: nil, last_name: nil, email: "user2@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-10-27 12:57:57], updated_at: ~N[2023-10-27 12:57:57], ...>, #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "e4808008-febc-47e9-a38d-f6073145ec8f", first_name: "Ye", last_name: "Bo", email: "yebo@gmail.com", confirmed_at: nil, role: :superuser, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-10-27 13:01:05], updated_at: ~N[2023-10-27 13:01:05], ...> (truncated)
      ```
    </details>

**Expected behavior** 
I should be able to save the project with the newly updated name

**Screenshots**

https://github.com/OpenFn/Lightning/assets/6592749/74e46aaa-48ef-4008-a731-4b70e87ec971

**Comment by stuartc** [comment]
Can't recreate this as of ae010c117881c9093cebe6f46f3dba6465dbf45f.
