### ISSUE TITLE
SetupUtils failing, cannot reset demo properly

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1273]
@midigofrank and @elias-ba  it looks like [this commit](https://github.com/OpenFn/Lightning/commit/da83f50e9bb10a9c95f1cf8f7d4aabcb795c7ed0#diff-d37d07a1587c69afed99d4bf6200d0f7dba6afdba1cb93314cf887e15512af59) removes a lot of critical functionality from `SetupUtils` and I can't find any later commits that put it back. **How did you test this?** Here's how I'm testing `Lightning.Demo.reset_demo()`

First, something about the initial workorder isn't right... as you can see below, the created workorder doesn't match the initial filters anymore:
<img width="1193" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/4c654f67-0f69-4476-a63b-495d8bb4d818">

Then, it looks as if the state of the workorders, attempts, and runs are not being properly set:

<img width="1199" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/343dee6e-25b9-4f04-8b81-859850cc29ab">

At: commit `8bd870af1baa97915b096079957c72a5987c18d9`

```ex
INSERT INTO "workflow_edges" ("id","workflow_id","condition","target_job_id","source_job_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7) ["18258132-d45b-4296-be03-67f976a45bfb", "0b248a2e-613e-4ade-beb8-b812ecd539e2", :on_job_failure, "be74cfdf-48d1-4d16-8250-2d7ef5dea9b3", "8cdac588-30f8-4f3f-a955-b658af356c1d", ~N[2023-11-05 06:41:43], ~N[2023-11-05 06:41:43]]
** (RuntimeError) :workorder is already a member of the Ecto.Multi: 
%Ecto.Multi{operations: [attempt: {:run, #Function<16.113720088/2 in Ecto.Multi.operation_fun/2>}, workorder: {:changeset, #Ecto.Changeset<action: :insert, changes: %{workflow: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Workflow<>, valid?: true>, trigger: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Trigger<>, valid?: true>, dataclip: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Invocation.Dataclip<>, valid?: true>, attempts: [#Ecto.Changeset<action: :insert, changes: %{dataclip: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Invocation.Dataclip<>, valid?: true>, starting_trigger: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Trigger<>, valid?: true>}, errors: [], data: #Lightning.Attempt<>, valid?: true>]}, errors: [], data: #Lightning.WorkOrder<>, valid?: true>, []}], names: MapSet.new([:workorder, :attempt])}
    (ecto 3.10.3) lib/ecto/multi.ex:693: Ecto.Multi.add_operation/3
    (lightning 0.10.0-pre) lib/lightning/setup_utils.ex:927: Lightning.SetupUtils.create_workorder/4
    (lightning 0.10.0-pre) lib/lightning/setup_utils.ex:613: Lightning.SetupUtils.create_openhie_project/1
    (lightning 0.10.0-pre) lib/lightning/setup_utils.ex:45: Lightning.SetupUtils.setup_demo/1
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    (lightning 0.10.0-pre) lib/lightning/demo.ex:21: Lightning.Demo.reset_demo/0
    iex:1: (file)
```

**Comment by taylordowns2000** [comment]
@midigofrank , @elias-ba , as of [`a4cec706ba039f95faa9229bd81e5e7119092125`](https://github.com/OpenFn/Lightning/commit/a4cec706ba039f95faa9229bd81e5e7119092125) we're almost back to a working pattern with the "openhie-project" demo. 

Please:

- [ ] Ensure that the input/output dataclips for all of the runs in the OpenHIE project are there. (I just see `null` right now.)
- [ ] Ensure that the original input dataclip from the OpenHIE workorder is there. (I see a blank box when I click into it.)
- [ ] Fix the dhis2 project setup script along the same lines as my work on OpenHIE.

For DHIS2, I think that a lot of the business context was lost [here](https://github.com/OpenFn/Lightning/commit/da83f50e9bb10a9c95f1cf8f7d4aabcb795c7ed0#diff-d37d07a1587c69afed99d4bf6200d0f7dba6afdba1cb93314cf887e15512af59).

After you run `Lightning.Demo.reset_demo`, navigate to the dhis2 history page and look carefully at everything you see there to ensure it tells a logical story.
