### ISSUE TITLE
Offline usage throwing adaptor service errors when adding jobs to canvas

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1436]
When building workflows without a connection to the internet (or with low connectivity) I'm seeing this error:

```
SELECT p0."id", p0."credential_id", p0."project_id", p0."inserted_at", p0."updated_at" FROM "project_credentials" AS p0 WHERE (p0."project_id" = $1) ["4adf2644-ed4e-4f97-a24c-ab35b3cb1efa"]
[error] Task #PID<0.1670.0> started from Lightning.AdaptorRegistry terminating
** (HTTPoison.Error) :timeout
    (lightning 0.10.2) lib/lightning/adaptor_registry.ex:46: Lightning.AdaptorRegistry.Npm.request!/5
    (lightning 0.10.2) lib/lightning/adaptor_registry.ex:84: Lightning.AdaptorRegistry.Npm.package_detail/1
    (lightning 0.10.2) lib/lightning/adaptor_registry.ex:253: Lightning.AdaptorRegistry.fetch_npm_details/1
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<3.61948593/1 in Lightning.AdaptorRegistry.fetch_npm_details>, ["@openfn/language-cartodb"]]
[info] Starting AdaptorRegistry
[debug] Fetching adaptors from NPM.
[error] GenServer #PID<0.1604.0> terminating
** (stop) exited in: GenServer.call(Lightning.AdaptorRegistry, :all, 30000)
    ** (EXIT) an exception was raised:
        ** (HTTPoison.Error) :timeout
            (lightning 0.10.2) lib/lightning/adaptor_registry.ex:46: Lightning.AdaptorRegistry.Npm.request!/5
            (lightning 0.10.2) lib/lightning/adaptor_registry.ex:84: Lightning.AdaptorRegistry.Npm.package_detail/1
            (lightning 0.10.2) lib/lightning/adaptor_registry.ex:253: Lightning.AdaptorRegistry.fetch_npm_details/1
            (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
            (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
    (elixir 1.15.4) lib/gen_server.ex:1074: GenServer.call/3
    (lightning 0.10.2) lib/lightning_web/live/job_live/adaptor_picker.ex:94: LightningWeb.JobLive.AdaptorPicker.get_adaptor_version_options/1
    (lightning 0.10.2) lib/lightning_web/live/job_live/adaptor_picker.ex:60: LightningWeb.JobLive.AdaptorPicker.update/2
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/utils.ex:498: Phoenix.LiveView.Utils.maybe_call_update!/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:659: anonymous fn/6 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:635: anonymous fn/4 in Phoenix.LiveView.Diff.render_pending_components/6
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:629: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:919: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:775: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5oHowkwK4A_ayBD", event: "live_patch", payload: %{"url" => "http://localhost:4000/projects/4adf2644-ed4e-4f97-a24c-ab35b3cb1efa/w/bc6f2edf-8535-4f7c-8ebd-308240ba659c?s=fbe7b688-4391-4f21-b3ae-3123351c1e37"}, ref: "19", join_ref: "11"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F5oHowkwK4A_ayBD", endpoint: LightningWeb.Endpoint, view: LightningWeb.WorkflowLive.Edit, parent_pid: nil, root_pid: #PID<0.1604.0>, router: LightningWeb.Router, assigns: %{project: %Lightning.Projects.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", name: "openhie-project", description: nil, scheduled_deletion: nil, requires_mfa: false, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>, project_credentials: #Ecto.Association.NotLoaded<association :project_credentials is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, workflows: #Ecto.Association.NotLoaded<association :workflows is not loaded>, jobs: #Ecto.Association.NotLoaded<association :jobs is not loaded>, inserted_at: ~N[2023-11-22 18:57:55], updated_at: ~N[2023-11-22 18:57:55]}, __changed__: %{}, current_user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "3dbb776c-4634-470e-a20b-9391b13606a0", first_name: "Amy", last_name: "Admin", email: "demo@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2023-11-22 18:57:54], updated_at: ~N[2023-11-22 18:57:54], ...>, flash: %{}, changeset: #Ecto.Changeset<action: nil, changes: %{edges: [#Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Edge<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Edge<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Edge<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Edge<>, valid?: true>, #Ecto.Changeset<action: :insert, changes: %{id: "e4ddf262-0373-4cf0-b68b-2c00b58783e6", target_job_id: "fbe7b688-4391-4f21-b3ae-3123351c1e37", source_job_id: "2a483c54-eec1-45a6-8223-e81147ee290c", condition: :on_job_success}, errors: [], data: #Lightning.Workflows.Edge<>, valid?: true>], jobs: [#Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Job<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Job<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Job<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #Lightning.Workflows.Job<>, valid?: true>, #Ecto.Changeset<action: :insert, changes: %{id: "fbe7b688-4391-4f21-b3ae-3123351c1e37", name: "final catch", body: "// Get started by adding operations from the API reference\n"}, errors: [], data: #Lightning.Workflows.Job<>, valid?: true>]}, errors: [], data: #Lightning.Workflows.Workflow<>, valid?: true>, active_menu_item: :overview, projects: [%Lightning.Projects.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", name: "openhie-project", description: nil, scheduled_deletion: nil, requires_mfa: false, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>, project_credentials: #Ecto.Association.NotLoaded<association :project_credentials is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, workflows: #Ecto.Association.NotLoaded<association :workflows is not loaded>, jobs: #Ecto.Association.NotLoaded<association :jobs is not loaded>, inserted_at: ~N[2023-11-22 18:57:55], updated_at: ~N[2023-11-22 18:57:55]}, %Lightning.Projects.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, id: "36fe0404-5b20-4283-aeaf-490e0332bba6", name: "dhis2-project", description: nil, scheduled_deletion: nil, requires_mfa: false, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>, project_credentials: #Ecto.Association.NotLoaded<association :project_credentials is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, workflows: #Ecto.Association.NotLoaded<association :workflows is not loaded>, jobs: #Ecto.Association.NotLoaded<association :jobs is not loaded>, inserted_at: ~N[2023-11-22 18:57:55], updated_at: ~N[2023-11-22 18:57:55]}], page_title: "OpenHIE Workflow", workflow_name: "", project_user: %Lightning.Projects.ProjectUser{__meta__: #Ecto.Schema.Metadata<:loaded, "project_users">, id: "eb3dbc10-24f4-4647-b6c3-28978c826b50", user_id: "3dbb776c-4634-470e-a20b-9391b13606a0", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "3dbb776c-4634-470e-a20b-9391b13606a0", first_name: "Amy", last_name: "Admin", email: "demo@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Asso (truncated)
```

**Comment by taylordowns2000** [comment]
fixed with Frank's offline work for MSF
