### ISSUE TITLE
Selecting a job node with a slow internet causes a `:timeout` error

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/lightning#1739]
**Describe the bug** A clear and concise description of what the bug is.

When you select a node in a workflow with a slow internet (or no internet at all), the app crashes with the following HTTPoison timeout error.

```
[error] Task #PID<0.7362.0> started from Lightning.AdaptorRegistry terminating
** (HTTPoison.Error) :timeout
    (lightning 2.0.0) lib/lightning/adaptor_registry.ex:46: Lightning.AdaptorRegistry.Npm.request!/5
    (lightning 2.0.0) lib/lightning/adaptor_registry.ex:84: Lightning.AdaptorRegistry.Npm.package_detail/1
    (lightning 2.0.0) lib/lightning/adaptor_registry.ex:253: Lightning.AdaptorRegistry.fetch_npm_details/1
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<3.61948593/1 in Lightning.AdaptorRegistry.fetch_npm_details>, ["@openfn/language-azure-storage"]]
```

**Version number** The version of Lightning you have seen the bug on.

This is happening on main. My git head is at `93a51614a737620020e1c4f82997b64bc855de6d` at the time I got the error.

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Launch Lightning with a slow internet / or no internet
2. Go to the workflow canvas and select a job node
3. See the app crashing and the job panel not opening
4. See error in your iex server

**Expected behavior** A clear and concise description of what you expected to
happen.

Instead of the app crashing we should handle the timeout error in the `AdaptorRegistry` and display an informative error message

**Comment by christad92** [comment]
@elias-ba i have tried to replicate this bug but I couldn't. Please see the video below for my most recent attempt at replicating it. 

https://www.loom.com/share/cb48a27b06714a64b09ea88445d5519f?sid=4882bbbe-097a-4c61-94df-b2a1a549a34b

**Comment by christad92** [comment]
I couldn't reproduce this error again, but I noticed that the app kept reloading. At some point, it showed the lost connection icon and reloaded again. This kept happening endlessly. 

I think we should be able to show a message saying the connection is not great and avoid the endless reloads. I also noticed that the app loads every time a job is selected, can we possibly lazy load the resources without overloading memory? This way, we don't need to make API calls every time a job is selected.

![Image](https://github.com/user-attachments/assets/27b7822d-5142-43a4-b8e5-c0a457563323)
