### ISSUE TITLE
KhanAcademy credential schema not working

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1751]
Trying to create a KhanAcademy credential throws a no case clause match error once you type anything into the email field.

```ex
[error] GenServer #PID<0.1490.0> terminating
** (CaseClauseError) no case clause matching: %ExJsonSchema.Validator.Error.Format{expected: "email"}
    (lightning 2.0.0) lib/lightning/credentials/schema.ex:98: Lightning.Credentials.Schema.error_to_changeset/2
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (lightning 2.0.0) lib/lightning_web/live/credential_live/json_schema_body_component.ex:16: LightningWeb.CredentialLive.JsonSchemaBodyComponent."fieldset (overridable 1)"/1
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/tag_engine.ex:69: Phoenix.LiveView.TagEngine.component/3
    (lightning 2.0.0) lib/lightning_web/live/credential_live/form_component.ex:488: anonymous fn/2 in LightningWeb.CredentialLive.FormComponent."form_component (overridable 1)"/1
    (lightning 2.0.0) /Users/taylor/build/lightning/lib/lightning_web/live/credential_live/form_component.ex:350: LightningWeb.CredentialLive.FormComponent.render/1
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:366: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:366: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:366: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:366: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F7N6tFjJQlEpfgrj", event: "event", payload: %{"cid" => 1, "event" => "validate", "type" => "form", "uploads" => %{}, "value" => "credential%5Bname%5D=&credential%5Bproduction%5D=false&credential%5Bbody%5D%5Bemail%5D=d&credential%5Bbody%5D%5Bpassword%5D=&credential%5Bbody%5D%5BconsumerKey%5D=&credential%5Bbody%5D%5BsecretKey%5D=&_target=credential%5Bbody%5D%5Bemail%5D"}, ref: "167", join_ref: "162"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F7N6tFjJQlEpfgrj", endpoint: LightningWeb.Endpoint, view: LightningWeb.ProjectLive.Settings, parent_pid: nil, root_pid: #PID<0.1490.0>, router: LightningWeb.Router, assigns: %{credentials: [#Lightning.Credentials.Credential<__meta__: #Ecto.Schema.Metadata<:loaded, "credentials">, id: "2748c06b-a7b9-4f05-aa5c-cadaf498c579", name: "elias 10", production: false, schema: "asana", scheduled_deletion: nil, user_id: "804a9c50-c4da-45de-9d70-ddc6a31d6f89", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "804a9c50-c4da-45de-9d70-ddc6a31d6f89", first_name: "Sizwe", last_name: "Super", email: "super@openfn.org", confirmed_at: nil, role: :superuser, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2024-01-22 10:11:12], updated_at: ~N[2024-01-22 10:11:12], ...>, project_credentials: [%Lightning.Projects.ProjectCredential{__meta__: #Ecto.Schema.Metadata<:loaded, "project_credentials">, id: "04d77d46-6917-444a-8e89-a8f12696c4ef", credential_id: "2748c06b-a7b9-4f05-aa5c-cadaf498c579", credential: #Ecto.Association.NotLoaded<association :credential is not loaded>, project_id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: false, inserted_at: ~N[2024-02-12 15:44:24], updated_at: ~N[2024-02-12 15:44:24]}], projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, inserted_at: ~U[2024-02-12 15:44:24Z], updated_at: ~U[2024-02-13 17:04:11Z], ...>, #Lightning.Credentials.Credential<__meta__: #Ecto.Schema.Metadata<:loaded, "credentials">, id: "2936c6db-e596-4263-8faa-80b296d9c26f", name: "test2", production: false, schema: "raw", scheduled_deletion: nil, user_id: "c23dc682-c138-440f-9e10-62488bb65a6e", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "c23dc682-c138-440f-9e10-62488bb65a6e", first_name: "Amy", last_name: "Admin", email: "demo@openfn.org", confirmed_at: nil, role: :user, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2024-01-22 10:11:13], updated_at: ~N[2024-01-22 10:11:13], ...>, project_credentials: [%Lightning.Projects.ProjectCredential{__meta__: #Ecto.Schema.Metadata<:loaded, "project_credentials">, id: "8930d72d-ecc4-4870-bc20-c1e6eac2a622", credential_id: "2936c6db-e596-4263-8faa-80b296d9c26f", credential: #Ecto.Association.NotLoaded<association :credential is not loaded>, project_id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: false, inserted_at: ~N[2024-02-06 17:10:56], updated_at: ~N[2024-02-06 17:10:56]}], projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, inserted_at: ~U[2024-02-06 17:10:55Z], updated_at: ~U[2024-02-06 17:10:55Z], ...>, #Lightning.Credentials.Credential<__meta__: #Ecto.Schema.Metadata<:loaded, "credentials">, id: "48300e4e-81e1-430e-8cd6-5cc19d64eaae", name: "okelis1", production: false, schema: "cartodb", scheduled_deletion: nil, user_id: "804a9c50-c4da-45de-9d70-ddc6a31d6f89", user: #Lightning.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "804a9c50-c4da-45de-9d70-ddc6a31d6f89", first_name: "Sizwe", last_name: "Super", email: "super@openfn.org", confirmed_at: nil, role: :superuser, disabled: false, mfa_enabled: false, scheduled_deletion: nil, user_totp: #Ecto.Association.NotLoaded<association :user_totp is not loaded>, credentials: #Ecto.Association.NotLoaded<association :credentials is not loaded>, project_users: #Ecto.Association.NotLoaded<association :project_users is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, backup_codes: #Ecto.Association.NotLoaded<association :backup_codes is not loaded>, inserted_at: ~N[2024-01-22 10:11:12], updated_at: ~N[2024-01-22 10:11:12], ...>, project_credentials: [%Lightning.Projects.ProjectCredential{__meta__: #Ecto.Schema.Metadata<:loaded, "project_credentials">, id: "72b8f57c-4e5c-4234-9b63-746653d8f046", credential_id: "48300e4e-81e1-430e-8cd6-5cc19d64eaae", credential: #Ecto.Association.NotLoaded<association :credential is not loaded>, project_id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: false, inserted_at: ~N[2024-02-13 17:01:33], updated_at: ~N[2024-02-13 17:01:33]}], projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, inserted_at: ~U[2024-02-13 17:01:33Z], updated_at: ~U[2024-02-13 17:01:46Z], ...>, #Lightning.Credentials.Credential<__meta__: #Ecto.Schema.Metadata<:loaded, "credentials">, id (truncate
```

**Comment by taylordowns2000** [comment]
fixed
