### ISSUE TITLE
Make defaul.css import compatible with umbrella

### ISSUE THREAD

**Issue by jyeshe** [OpenFn/lightning#1775]
Building Lighting from an umbrella app gives this error on `$ mix tailwind default --minify`:

```
Error: Failed to find '../../deps/petal_components/assets/default.css'
  in [
    /home/rogerio/Workspace/openfn/umbrella/apps/lightning/assets/css
  ]
    at /snapshot/tailwindcss/node_modules/postcss-import/lib/resolve-id.js:35:13
    at async LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:396:11)
    at async build (/snapshot/tailwindcss/lib/cli/build/index.js:49:9)
** (Mix) `mix tailwind default --minify` exited with 1
```

The cause is this hardcoded path:
./apps/lightning/assets/css/app.css:6:@import '../../deps/petal_components/assets/default.css';

**Version number** 

2.0.0

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** 

1. Create an umbrella app
2. Clone lighting repo under apps
3. Run `mix setup` on the umbrella root
4. Run `mix assets.deploy`

**Comment by christad92** [comment]
We want to be able to build TB's assets at a TB level instead of the at a LT level. It is NOT blocking engineering at the moment.
