### ISSUE TITLE
the data retention purging is failing—queries taking too long

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2528]
Oban job for purging work orders and data clips after the data retention period is exceeded fails with connection error due to timeout or termination of the pool. 

```
{"{\"at\": \"2024-09-22T02:02:40.643700Z\", \"error\": \"** (DBConnection.ConnectionError) 
tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because 
the pool has been terminated)\\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
\\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\\n (ecto 3.11.2)
lib/ecto/multi.ex:949: anonymous fn/4 in Ecto.Multi.operation_fun/2\\n (ecto 3.11.2) lib/ecto/multi.ex:883:Ecto.Multi.apply_operation/5\\n (elixir 1.16.2) lib/enum.ex:2528: Enum.\\\"-reduce/3-lists^foldl/2-0-\\\"/3
\\n (ecto 3.11.2) lib/ecto/multi.ex:856: anonymous fn/5 in Ecto.Multi.apply_operations/5
\\n (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4\\n (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4\\n\", \"attempt\": 1}"}
```

**Comment by christad92** [comment]
Can we increase the timeout for this feature? This is probably the cheapest way to fix this. 

cc: @stuartc
