### ISSUE TITLE
Collections: 500 returned if an item doesn't exist

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/lightning#2733]
If I request a single item for a collection, and that item does not exist, I get a 500 error back from Lightning, with this payload
```
# unhandled exit at GET /collections/stuff/z

Exception:

    ** (exit) {:response_error, :payload_too_large, :"204 and 304 responses must not include a body. (RFC7230 3.3)"}
        (cowboy 2.12.0) /d/repo/openfn/lightning/deps/cowboy/src/cowboy_req.erl:846: :cowboy_req.do_reply_ensure_no_body/4
        (plug_cowboy 2.7.2) lib/plug/cowboy/conn.ex:35: Plug.Cowboy.Conn.send_resp/4
        (plug 1.16.1) lib/plug/conn.ex:444: Plug.Conn.send_resp/1
        (lightning 2.10.4) lib/lightning_web/controllers/collections_controller.ex:1: LightningWeb.CollectionsController.action/2
        (lightning 2.10.4) lib/lightning_web/controllers/collections_controller.ex:1: LightningWeb.CollectionsController.phoenix_controller_pipeline/2
        (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
        (lightning 2.10.4) lib/lightning_web/endpoint.ex:1: LightningWeb.Endpoint.plug_builder_call/2
        (lightning 2.10.4) lib/lightning_web/endpoint.ex:1: LightningWeb.Endpoint."call (overridable 3)"/2
        (lightning 2.10.4) deps/plug/lib/plug/debugger.ex:136: LightningWeb.Endpoint."call (overridable 4)"/2
        (lightning 2.10.4) lib/lightning_web/endpoint.ex:1: LightningWeb.Endpoint.call/2
        (phoenix 1.7.14) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.7.2) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.12.0) /d/repo/openfn/lightning/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.12.0) /d/repo/openfn/lightning/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.12.0) /d/repo/openfn/lightning/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    

Code:

`/d/repo/openfn/lightning/deps/cowboy/src/cowboy_req.erl`

    No code available.

`lib/plug/cowboy/conn.ex`

    30   
    31     @impl true
    32     def send_resp(req, status, headers, body) do
    33       req = to_headers_map(req, headers)
    34       status = Integer.to_string(status) &lt;&gt; &quot; &quot; &lt;&gt; Plug.Conn.Status.reason_phrase(status)
    35>      req = :cowboy_req.reply(status, %{}, body, req)
    36       {:ok, nil, req}
    37     end
    38   
    39     @impl true
    40     def send_file(req, status, headers, path, offset, length) do
    
`lib/plug/conn.ex`

    439   
    440     def send_resp(%Conn{adapter: {adapter, payload}, state: :set, owner: owner} = conn) do
    441       conn = run_before_send(conn, :set)
    442   
    443       {:ok, body, payload} =
    444>        adapter.send_resp(payload, conn.status, conn.resp_headers, conn.resp_body)
    445   
    446       send(owner, @already_sent)
    447       %{conn | adapter: {adapter, payload}, resp_body: body, state: :sent}
    448     end
    449   
    
`lib/lightning_web/controllers/collections_controller.ex`

    1>  defmodule LightningWeb.CollectionsController do
    2     use LightningWeb, :controller
    3   
    4     alias Lightning.Collections
    5     alias Lightning.Policies.Permissions
    6   
    
`lib/lightning_web/controllers/collections_controller.ex`

    1>  defmodule LightningWeb.CollectionsController do
    2     use LightningWeb, :controller
    3   
    4     alias Lightning.Collections
    5     alias Lightning.Policies.Permissions
    6   
    
`lib/phoenix/router.ex`

    479           :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    480           halted_conn
    481   
    482         %Plug.Conn{} = piped_conn -&gt;
    483           try do
    484>            plug.call(piped_conn, plug.init(opts))
    485           else
    486             conn -&gt;
    487               measurements = %{duration: System.monotonic_time() - start}
    488               metadata = %{metadata | conn: conn}
    489               :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    
`lib/lightning_web/endpoint.ex`

    1>  defmodule LightningWeb.Endpoint do
    2     use Sentry.PlugCapture
    3     use Phoenix.Endpoint, otp_app: :lightning
    4     alias LightningWeb.Plugs
    5   
    6     # The session will be stored in the cookie and signed,
    
`lib/lightning_web/endpoint.ex`

    1>  defmodule LightningWeb.Endpoint do
    2     use Sentry.PlugCapture
    3     use Phoenix.Endpoint, otp_app: :lightning
    4     alias LightningWeb.Plugs
    5   
    6     # The session will be stored in the cookie and signed,
    
`deps/plug/lib/plug/debugger.ex`

    131             case conn do
    132               %Plug.Conn{path_info: [&quot;__plug__&quot;, &quot;debugger&quot;, &quot;action&quot;], method: &quot;POST&quot;} -&gt;
    133                 Plug.Debugger.run_action(conn)
    134   
    135               %Plug.Conn{} -&gt;
    136>                super(conn, opts)
    137             end
    138           rescue
    139             e in Plug.Conn.WrapperError -&gt;
    140               %{conn: conn, kind: kind, reason: reason, stack: stack} = e
    141               Plug.Debugger.__catch__(conn, kind, reason, stack, @plug_debugger)
    
`lib/lightning_web/endpoint.ex`

    1>  defmodule LightningWeb.Endpoint do
    2     use Sentry.PlugCapture
    3     use Phoenix.Endpoint, otp_app: :lightning
    4     alias LightningWeb.Plugs
    5   
    6     # The session will be stored in the cookie and signed,
    
`lib/phoenix/endpoint/sync_code_reload_plug.ex`

    17   
    18     def call(conn, {endpoint, opts}), do: do_call(conn, endpoint, opts, true)
    19   
    20     defp do_call(conn, endpoint, opts, retry?) do
    21       try do
    22>        endpoint.call(conn, opts)
    23       rescue
    24         exception in [UndefinedFunctionError] -&gt;
    25           case exception do
    26             %UndefinedFunctionError{module: ^endpoint} when retry? -&gt;
    27               # Sync with the code reloader and retry once
    
`lib/plug/cowboy/handler.ex`

    6     def init(req, {plug, opts}) do
    7       conn = @connection.conn(req)
    8   
    9       try do
    10         conn
    11>        |&gt; plug.call(opts)
    12         |&gt; maybe_send(plug)
    13         |&gt; case do
    14           %Plug.Conn{adapter: {@connection, %{upgrade: {:websocket, websocket_args}} = req}} = conn -&gt;
    15             {handler, state, cowboy_opts} = websocket_args
    16             {__MODULE__, copy_resp_headers(conn, req), {handler, state}, cowboy_opts}
    
`/d/repo/openfn/lightning/deps/cowboy/src/cowboy_handler.erl`

    No code available.

`/d/repo/openfn/lightning/deps/cowboy/src/cowboy_stream_h.erl`

    No code available.

`/d/repo/openfn/lightning/deps/cowboy/src/cowboy_stream_h.erl`

    No code available.

`proc_lib.erl`

    No code available.


## Connection details

### Params

    %{}

### Request info

  * URI: http://localhost:4000/collections/stuff/z
  * Query string: 

### Headers
  
  * authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA5OTYxNzksImlzcyI6IkxpZ2h0bmluZyIsImp0aSI6IjMwMnJubWxpMXY5MWJmdHA0ZzAwMDd1MSIsInN1YiI6InVzZXI6NTY0ZTc5ZDMtNjVlNC00ZWM1LWE2NmQtM2FlOTIzMmY4YjVhIn0.H4XNJuD704rw3GEcTAR7iyldGiMo2fc4PUtQzmM2VNNG7SSV2MNdyB6vqaOIWp-aDFa150jlpHT9S_cHzaNiVsPiH6-ewquaF06iMV7egbjivoJjl1r4V3d_jxcaWPU8wly0dp7y4lnTFIxfTypzDPjM-o1_gLkClpO2tjgqogPnXNhqugp7xlj69xS8-AsGmbvvj65PbQHo4vgMYp-hnUntXECrr79p4V4iyDkVHVNEwUp6-Veh3zLVs07v4hUMFVOUZq-oKGbDXl1audlHLZp1cFxqnvjQrIsSOaQNdRDKjwOX6S572cjCtnlMPtZTdiHbHs8Gz4fWG0ugSPTSqA
  * connection: keep-alive
  * host: localhost:4000

### Session

    nil
```
Any ideas?

**Comment by josephjclark** [comment]
I can repro with curl (collection `stuff` exists, item  `zzz` does not, and existing items are fine)
```
curl -X GET "http://localhost:4000/collections/stuff/zzz" -H "Authorization: Bearer $LOCAL_LIGHTNING_PAT" 
```
