### ISSUE TITLE
maybe_add_workflow gets called on EVERY form change, not only on save

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#329]
the `maybe_add_workflow` function appears to get called on every form change. this produces two undesirable results:

1. we get 500s and unresponsiveness if you try to change the trigger type from a `cron` or `webhook` to either `on_job_success` or `on_job_failure`. the crash happens because that maybe_add_workflow is trying to actually create a new workflow, even though the user hasn't yet specified _which_ upstream job they're reparenting to. see error below.

2. workflows get created on every form change. see video on slack. to reproduce this, change an existing job's trigger type from any kind of flow to either `cron` or `webhook`. you'll see a new workflow instantly created in the db. from here on out, every keystroke or form event will create a new workflow.

```ex
[error] GenServer #PID<0.1191.0> terminating
** (ArgumentError) cannot perform Ecto.Repo.get/2 because the given value is nil
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:434: Ecto.Repo.Queryable.query_for_get/2
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:65: Ecto.Repo.Queryable.get/4
    (lightning 0.1.13) lib/lightning/jobs/job.ex:125: Lightning.Jobs.Job.maybe_add_workflow/1
    (lightning 0.1.13) lib/lightning/jobs/job.ex:77: Lightning.Jobs.Job.changeset/2
    (lightning 0.1.13) lib/lightning_web/live/job_live/form_component.ex:79: LightningWeb.JobLive.FormComponent.validate/2
    (lightning 0.1.13) lib/lightning_web/live/job_live/inspector_form_component.ex:15: LightningWeb.JobLive.InspectorFormComponent.handle_event/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/channel.ex:600: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
```

cc @amberrignell , we can release 0.2.0 when this is sorted. all else looks good.

**Comment by taylordowns2000** [comment]
Ooh also, @elias-ba and @stuartc , this is the perfect time to discuss https://github.com/OpenFn/Lightning/issues/290 .

@elias-ba , can you come ready to discuss this bug and the "when do we use different changesets" for form validation and on-save events question when we meet for standup on Monday?
