### ISSUE TITLE
trunctation error - value too long for type character varying(255)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#533]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Run the following job
```
get("https://api.chucknorris.io/jokes/random");

fn(state=> {
    console.log(state)
    return state;
})
``` 

2. See error below

```
[error] Oban exception:
%Postgrex.Error{message: nil, postgres: %{code: :string_data_right_truncation, file: "varchar.c", line: "632", message: "value too long for type character varying(255)", pg_code: "22001", routine: "varchar", severity: "ERROR", unknown: "ERROR"}, connection_id: 488, query: nil}
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.9.1) lib/ecto/repo/schema.ex:756: Ecto.Repo.Schema.apply/4
    (ecto 3.9.1) lib/ecto/repo/schema.ex:459: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (lightning 0.3.1) lib/lightning/invocation.ex:270: Lightning.Invocation.update_run/2
    (lightning 0.3.1) lib/lightning/pipeline/runner.ex:38: Lightning.Pipeline.Runner.Handler.on_finish/2
    (lightning 0.3.1) lib/lightning/runtime/handler.ex:109: Lightning.Pipeline.Runner.Handler.wait/1
    (lightning 0.3.1) lib/lightning/pipeline.ex:29: Lightning.Pipeline.process/1
    (oban 2.13.5) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
    (oban 2.13.5) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

meta:
  %{
  args: %{"attempt_run_id" => "692e8995-fa69-4394-97a6-5ebfcdcc69c1"},
  attempt: 1,
  conf: %Oban.Config{
    dispatch_cooldown: 100,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    log: false,
    name: Oban,
    node: "fn",
    notifier: Oban.Notifiers.Postgres,
    peer: Oban.Peers.Postgres,
    plugins: [
      {Oban.Plugins.Cron,
       [
         crontab: [
           {"* * * * *", Lightning.Jobs.Scheduler},
           {"* * * * *", ObanPruner},
           {"0 2 * * *", Lightning.Accounts,
            [args: %{"type" => "purge_deleted"}]}
         ]
       ]},
      Oban.Plugins.Stager
    ],
    prefix: "public",
    queues: [scheduler: [limit: 1], background: [limit: 1], runs: [limit: 1]],
    repo: Lightning.Repo,
    shutdown_grace_period: 60000,
    testing: :disabled
  },
  id: 355,
  job: %Oban.Job{
    __meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">,
    id: 355,
    state: "executing",
    queue: "runs",
    worker: "Lightning.Pipeline",
    args: %{"attempt_run_id" => "692e8995-fa69-4394-97a6-5ebfcdcc69c1"},
    meta: %{},
    tags: [],
    errors: [],
    attempt: 1,
    attempted_by: ["fn"],
    max_attempts: 1,
    priority: 1,
    attempted_at: ~U[2023-01-02 09:38:38.445681Z],
    cancelled_at: nil,
    completed_at: nil,
    discarded_at: nil,
    inserted_at: ~U[2023-01-02 09:38:38.330901Z],
    scheduled_at: ~U[2023-01-02 09:38:38.330901Z],
    conf: %Oban.Config{
      dispatch_cooldown: 100,
      engine: Oban.Engines.Basic,
      get_dynamic_repo: nil,
      log: false,
      name: Oban,
      node: "fn",
      notifier: Oban.Notifiers.Postgres,
      peer: Oban.Peers.Postgres,
      plugins: [
        {Oban.Plugins.Cron,
         [
           crontab: [
             {"* * * * *", Lightning.Jobs.Scheduler},
             {"* * * * *", ObanPruner},
             {"0 2 * * *", Lightning.Accounts,
              [args: %{"type" => "purge_deleted"}]}
           ]
         ]},
        Oban.Plugins.Stager
      ],
      prefix: "public",
      queues: [scheduler: [limit: 1], background: [limit: 1], runs: [limit: 1]],
      repo: Lightning.Repo,
      shutdown_grace_period: 60000,
      testing: :disabled
    },
    conflict?: false,
    replace: nil,
    unique: nil,
    unsaved_error: %{
      kind: :error,
      reason: %Postgrex.Error{
        message: nil,
        postgres: %{
          code: :string_data_right_truncation,
          file: "varchar.c",
          line: "632",
          message: "value too long for type character varying(255)",
          pg_code: "22001",
          routine: "varchar",
          severity: "ERROR",
          unknown: "ERROR"
        },
        connection_id: 488,
        query: nil
      },
      stacktrace: [
        {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
         [
           file: 'lib/ecto/adapters/sql.ex',
           line: 905,
           error_info: %{module: Exception}
         ]},
        {Ecto.Repo.Schema, :apply, 4,
         [file: 'lib/ecto/repo/schema.ex', line: 756]},
        {Ecto.Repo.Schema, :"-do_update/4-fun-3-", 15,
         [file: 'lib/ecto/repo/schema.ex', line: 459]},
        {Lightning.Invocation, :update_run, 2,
         [file: 'lib/lightning/invocation.ex', line: 270]},
        {Lightning.Pipeline.Runner.Handler, :on_finish, 2,
         [file: 'lib/lightning/pipeline/runner.ex', line: 38]},
        {Lightning.Pipeline.Runner.Handler, :wait, 1,
         [file: 'lib/lightning/runtime/handler.ex', line: 109]},
        {Lightning.Pipeline, :process, 1,
         [file: 'lib/lightning/pipeline.ex', line: 29]},
        {Oban.Queue.Executor, :perform, 1,
         [file: 'lib/oban/queue/executor.ex', line: 129]},
        {Oban.Queue.Executor, :call, 1,
         [file: 'lib/oban/queue/executor.ex', line: 74]},
        {Task.Supervised, :invoke_mfa, 2,
         [file: 'lib/task/supervised.ex', line: 89]},
        {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]},
        {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
      ]
    }
  },
  kind: :error,
  max_attempts: 1,
  prefix: "public",
  queue: "runs",
  reason: %Postgrex.Error{
    message: nil,
    postgres: %{
      code: :string_data_right_truncation,
      file: "varchar.c",
      line: "632",
      message: "value too long for type character varying(255)",
      pg_code: "22001",
      routine: "varchar",
      severity: "ERROR",
      unknown: "ERROR"
    },
    connection_id: 488,
    query: nil
  },
  state: :discard,
  tags: [],
  worker: "Lightning.Pipeline"
}
(%{duration: 2632281266, queue_time: 114780000})
```

**Expected behavior** A clear and concise description of what you expected to
happen.
no error

**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment]
this is now reproducing on circleci

**Comment by taylordowns2000** [comment]
@stuartc , @wanecode , (cc @mtuchi ) the array `inner_type` for run.log is a `:string` which is limited to 255 chars by default. Anytime there's a log-line that's longer than 255, this will blow up.

Should we set that inner_type for run.log to `:text` (unlimited) or should we set a longer `:string` length limit so it blows up _less often_?

I'd vote for unlimited, unless there's some massive performance hit to using postgres `text` rather than `varchar`.

**Comment by josephjclark** [comment]
Can't really speak for postgres with much authority, but I agree we should be able to emit lines longer than 255 chars.

A quick skim of the postgres docs makes me think `text` is appropriate.

> PostgreSQL provides the text type, which stores strings of any length. Although the type text is not in the SQL standard, several other SQL database management systems have it as well.

`text` isn't padded or anything so it can be varying. The docs go on to say that it doesn't really matter from a performance point of view.

So it looks like `inner_type` of `:text` is a reasonable solution
