### ISSUE TITLE
Fix flaky `test POST /users/register creates account and logs the user in`

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#534]
**Describe the bug** A clear and concise description of what the bug is.

`test POST /users/register creates account and logs the user in` - this gets a 302 redirection when the test expects a 200.

why might it sometimes redirect on cirlceCI but not on local machines?

```
error: expected response with status 200, got: 302, with body:
"<html><body>You are being <a href=\"/projects/02c307e7-83a4-4054-8135-582e0bd8a10f/w\">redirected</a>.</body></html>"
2) test POST /users/register creates account and logs the user in (LightningWeb.UserRegistrationControllerTest)
     test/lightning_web/controllers/user_registration_controller_test.exs:27
     ** (RuntimeError) expected response with status 200, got: 302, with body:
     "<html><body>You are being <a href=\"/projects/02c307e7-83a4-4054-8135-582e0bd8a10f/w\">redirected</a>.</body></html>"
     code: response = html_response(conn, 200)
     stacktrace:
       (phoenix 1.6.15) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.6.15) lib/phoenix/test/conn_test.ex:383: Phoenix.ConnTest.html_response/2
       test/lightning_web/controllers/user_registration_controller_test.exs:40: (test)
```

**Additional context** Add any other context about the problem here.

https://app.circleci.com/pipelines/github/OpenFn/Lightning/1704/workflows/5c1bc707-0d4e-432c-aff8-a29364b5d4b0/jobs/7714

**Comment by taylordowns2000** [comment]
https://elixirforum.com/t/troubleshooting-a-failed-test-302-redirect-instead-of-200/8779 - a lead 🔍
