### ISSUE TITLE
Unable to view history page when too many requests

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#723]
**Describe the bug** A clear and concise description of what the bug is.

**Version number** The version of Lightning you have seen the bug on.

If you're running on a tagged version, include the number: `vX.Y.Z`

If you're running locally with an unreleased version, the commit sha: `84b1bdc`

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to the benchmarking folder and follow intructions
2. Whilst the requests are being processed, head to the history page 
3. See error

**Expected behavior** A clear and concise description of what you expected to
happen.
The history page should load, and we should be able to see the requests coming in. 

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screenshot 2023-03-22 at 21 03 03](https://user-images.githubusercontent.com/36554605/226996905-a500d662-5c7f-4aa8-adce-1eb4507f351a.png)

**Additional context** Add any other context about the problem here.

Stack trace below:
```
[error] GenServer #PID<0.15677.0> terminating
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
    (scrivener_ecto 2.7.0) lib/scrivener/paginater/ecto/query.ex:56: Scrivener.Paginater.Ecto.Query.total_entries/4
    (scrivener_ecto 2.7.0) lib/scrivener/paginater/ecto/query.ex:17: Scrivener.Paginater.Ecto.Query.paginate/2
    (lightning 0.4.5) lib/lightning_web/live/run_live/index.ex:88: LightningWeb.RunLive.Index.apply_action/3
    (lightning 0.4.5) lib/lightning_web/live/run_live/index.ex:76: LightningWeb.RunLive.Index.handle_params/3
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/utils.ex:416: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
    (telemetry 1.2.1) /Users/amber/openfn/lightning/Lightning/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:452: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:1030: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"params" => %{"_csrf_token" => "BxpnFTU_Gy4DeU1ASx40GBQGLV0yPjwjMv3tgrhLB8usfVY5s_Z9yumb", "_live_referer" => "http://localhost:4000/projects/72791ead-7569-42b1-8a26-1eae209c238d/w", "_mounts" => 0, "_track_static" => ["http://localhost:4000/assets/fonts/inter.css", "http://localhost:4000/assets/fonts/fira-code.css", "http://localhost:4000/assets/app.css", "http://localhost:4000/assets/js/app.js"]}, "redirect" => "http://localhost:4000/projects/72791ead-7569-42b1-8a26-1eae209c238d/runs", "session" => "SFMyNTY.g2gDaAJhBXQAAAAIZAACaWRtAAAAFHBoeC1GMDdQa1p6UlljOUhNVHdDZAAMbGl2ZV9zZXNzaW9uaAJkAAdkZWZhdWx0bggAXJpJEZLHThdkAApwYXJlbnRfcGlkZAADbmlsZAAIcm9vdF9waWRkAANuaWxkAAlyb290X3ZpZXdkACBFbGl4aXIuTGlnaHRuaW5nV2ViLldvcmtmbG93TGl2ZWQABnJvdXRlcmQAGkVsaXhpci5MaWdodG5pbmdXZWIuUm91dGVyZAAHc2Vzc2lvbnQAAAAAZAAEdmlld2QAIEVsaXhpci5MaWdodG5pbmdXZWIuV29ya2Zsb3dMaXZlbgYA-FB5CocBYgABUYA.oRm9r4KmOc87Yl2_NE9I4IfV0YboTj3s6e9J7bgFc8M", "static" => "SFMyNTY.g2gDaAJhBXQAAAADZAAKYXNzaWduX25ld2wAAAADZAAIcHJvamVjdHNkAAdwcm9qZWN0ZAAMY3VycmVudF91c2VyamQABWZsYXNodAAAAABkAAJpZG0AAAAUcGh4LUYwN1BrWnpSWWM5SE1Ud0NuBgD4UHkKhwFiAAFRgA.-Ubq1D94YzpVIV2qu3pcKNIixTDyR3gHRFMTuK_4lm8"}, {#PID<0.15400.0>, #Reference<0.2255593384.2666790914.119386>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: LightningWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: "users_sessions:1jPYsgWebaQGrEVE04AERIZ3MKBdXZ6uS6PLzF82rpY=", joined: false, join_ref: "11", private: %{connect_info: %{session: %{"_csrf_token" => "JlTaRMsbAA83-Hm-gYwdKKQA", "live_socket_id" => "users_sessions:1jPYsgWebaQGrEVE04AERIZ3MKBdXZ6uS6PLzF82rpY=", "user_token" => <<214, 51, 216, 178, 5, 158, 109, 164, 6, 172, 69, 68, 211, 128, 4, 68, 134, 119, 48, 160, 93, 93, 158, 174, 75, 163, 203, 204, 95, 54, 174, 150>>}}}, pubsub_server: Lightning.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-F07PkZzRYc9HMTwC", transport: :websocket, transport_pid: #PID<0.15400.0>}}
State: #Reference<0.2255593384.2666790914.119388>
[error] an exception was raised:
    ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
        (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
        (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
        (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (ecto 3.9.4) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
        (scrivener_ecto 2.7.0) lib/scrivener/paginater/ecto/query.ex:56: Scrivener.Paginater.Ecto.Query.total_entries/4
        (scrivener_ecto 2.7.0) lib/scrivener/paginater/ecto/query.ex:17: Scrivener.Paginater.Ecto.Query.paginate/2
        (lightning 0.4.5) lib/lightning_web/live/run_live/index.ex:88: LightningWeb.RunLive.Index.apply_action/3
        (lightning 0.4.5) lib/lightning_web/live/run_live/index.ex:76: LightningWeb.RunLive.Index.handle_params/3
        (phoenix_live_view 0.18.16) lib/phoenix_live_view/utils.ex:416: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
        (telemetry 1.2.1) /Users/amber/openfn/lightning/Lightning/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:452: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
        (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:1030: Phoenix.LiveView.Channel.verified_mount/8
        (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
        (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
        (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
        (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by taylordowns2000** [comment]
This is an infrastructure/db configuration concern. I'm closing, but if you run into this as a Lightning system admin make sure to read and understand all the options for configuring your DB connection here: https://hexdocs.pm/db_connection/DBConnection.html#start_link/2-options
